var Point=function(){return function(b,a){this.x=b;this.y=a}}(),Euclidean;
(function(b){function a(a,c){return Math.sqrt(Math.pow(c.x-a.x,2)+Math.pow(c.y-a.y,2))}(function(a){a[a.high=0]="high";a[a.low=1]="low"})(b.CircleCrossPointMode||(b.CircleCrossPointMode={}));b.circleCrossPoint=function(f,c,b,g,h){var k=a(c,b);b=Math.atan2(b.y-c.y,b.x-c.x);var l=Math.acos(k/(2*g)),k=new Point(c.x+g*Math.cos(b+l),c.y+g*Math.sin(b+l));c=new Point(c.x+g*Math.cos(b-l),c.y+g*Math.sin(b-l));if(0==h)return a(f,k)>a(f,c)?a(f,k):a(f,c);if(1==h)return a(f,k)<a(f,c)?a(f,k):a(f,c)};b.length=a;
b.distanceBetweenPointAndLine=function(b,c,d){c=new Point(c.x+(d.x-c.x)/2,c.y+(d.y-c.y)/2);return a(b,c)}})(Euclidean||(Euclidean={}));var Orbital;
(function(b){b.orbitalPeriod=function(a,b,c){return 2*Math.PI*Math.sqrt(Math.pow(a+b,3)/c)};b.orbitalNightTime=function(a,b,c){b=a+b;return 2*Math.pow(b,2)/Math.sqrt(b*c)*Math.asin(a/b)};b.hohmannStartDeltaV=function(a,b,c,d){b=a+b;a+=c;return Math.sqrt(d/b)*(Math.sqrt(2*a/(b+a))-1)};b.hohmannFinishDeltaV=function(a,b,c,d){b=a+b;a+=c;return Math.sqrt(d/a)*(1-Math.sqrt(2*b/(b+a)))};b.slidePhaseAngle=function(a,b,c){return a/(1-b/c)}})(Orbital||(Orbital={}));
var CookieConnector=function(){function b(a,b){"undefined"===typeof b&&(b=new Date(2030,12,31));this.key=a;this.expires=b}b.prototype.saveCookie=function(a){a=JSON.stringify(a);document.cookie="{}"!=a?this.key+"\x3d"+encodeURIComponent(a)+"; expires\x3d"+this.expires.toUTCString():this.key+"\x3dnone; expires\x3d"+(new Date(0)).toUTCString()};b.prototype.loadCookie=function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++)if(-1!=a[b].indexOf(this.key))return JSON.parse(decodeURIComponent(a[b].split("\x3d")[1]))};
return b}(),AntennaType;(function(b){b[b.omni=0]="omni";b[b.dish=1]="dish"})(AntennaType||(AntennaType={}));
var Antenna=function(){return function(b,a,f,c){this.name=b;this.type=a;this.range=f;this.elcConsumption=c}}(),__extends=this.__extends||function(b,a){function f(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);f.prototype=a.prototype;b.prototype=new f},AntennaData=function(b){function a(){b.call(this,a.cookieKey);this.stockAntennas={"Reflectron DP-10":new Antenna("Reflectron DP-10",0,500,0.01),"Communotron 16":new Antenna("Communotron 16",0,2500,0.13),"CommTech EXP-VR-2T":new Antenna("CommTech EXP-VR-2T",
0,3E3,0.18),"Communotron 32":new Antenna("Communotron 32",0,5E3,0.6),"Comms DTS-M1":new Antenna("Comms DTS-M1",1,5E4,0.82),"Reflectron KR-7":new Antenna("Reflectron KR-7",1,9E4,0.82)};this.userAntennas={}}__extends(a,b);a.prototype.getAntenna=function(a){var b=this.stockAntennas[a];void 0==b&&(b=this.userAntennas[a]);return b};a.prototype.save=function(){this.saveCookie(this.userAntennas)};a.prototype.load=function(){this.userAntennas=this.loadCookie();return void 0==this.userAntennas?(this.userAntennas=
{},!1):!0};a.cookieKey="userAntenna";return a}(CookieConnector),Body=function(){return function(b,a,f,c,d){this.name=b;this.color=a;this.radius=f;this.stdGravParam=c;this.soi=d}}(),BodyData=function(b){function a(){b.call(this,a.cookieKey);this.stockBodies={Kerbol:new Body("Kerbol","rgb(255,242,0)",261600,1172332800,Number.POSITIVE_INFINITY),Moho:new Body("Moho","rgb(185,122,87)",250,168.60938,9646.663),Eve:new Body("Eve","rgb(163,73,164)",700,8171.7302,85109.365),Gilly:new Body("Gilly","rgb(239,228,176)",
13,0.0082894498,126.12327),Kerbin:new Body("Kerbin","rgb(63,111,40)",600,3531.6,84159.286),Mun:new Body("Mun","rgb(127,127,127)",200,65.138398,2429.5591),Minmus:new Body("Minmus","rgb(153,217,234)",60,1.7658,2247.4284),Duna:new Body("Duna","rgb(237,28,36)",320,301.36321,47921.949),Ike:new Body("Ike","rgb(127,127,127)",130,18.568369,1049.5989),Dres:new Body("Dres","rgb(195,195,195)",138,21.484489,32832.84),Jool:new Body("Jool","rgb(92,231,58)",6E3,282528,2455985.2),Laythe:new Body("Laythe","rgb(25,55,98)",
500,1962,3723.6458),Vall:new Body("Vall","rgb(82,133,141)",300,207.4815,2406.4014),Tylo:new Body("Tylo","rgb(195,195,195)",600,4523.8934,10856.518),Bop:new Body("Bop","rgb(142,106,51)",65,2.4868349,1221.0609),Pol:new Body("Pol","rgb(206,211,1)",44,0.72170208,1042.1389),Eeloo:new Body("Eeloo","rgb(221,221,210)",210,74.410815,119082.94)};this.userBodies={}}__extends(a,b);a.prototype.getBody=function(a){var b=this.stockBodies[a];void 0==b&&(b=this.userBodies[a]);return b};a.prototype.save=function(){this.saveCookie(this.userBodies)};
a.prototype.load=function(){this.userBodies=this.loadCookie();return void 0==this.userBodies?(this.userBodies={},!1):!0};a.cookieKey="userBody";return a}(CookieConnector),Satellites=function(){function b(){this.body=new Body(void 0,void 0,void 0,void 0,void 0);this.antenna=new Antenna(void 0,void 0,void 0,void 0)}b.prototype.satPosition=function(a){var b=this.body.radius+this.altitude;return new Point(b*Math.cos(2*Math.PI/this.count*a),+b*Math.sin(2*Math.PI/this.count*a))};b.prototype.satDistance=
function(){return this.satDistanceTo(1)};b.prototype.satDistanceTo=function(a){return Euclidean.length(this.satPosition(0),this.satPosition(a))};b.prototype.isNextSatConnectable=function(){return this.canConnectToSat(1)};b.prototype.canConnectToSat=function(a){return this.count>=a+1&&Euclidean.length(this.satPosition(0),this.satPosition(a))<=this.antenna.range&&Euclidean.distanceBetweenPointAndLine(new Point(0,0),this.satPosition(0),this.satPosition(a))>this.body.radius};b.prototype.hasStableArea=
function(){return 3<=this.count&&this.isNextSatConnectable()};b.prototype.stableLimitAltitude=function(){return Euclidean.circleCrossPoint(new Point(0,0),this.satPosition(0),this.satPosition(1),this.antenna.range,0)-this.body.radius};b.prototype.orbitalPeriod=function(){return Orbital.orbitalPeriod(this.body.radius,this.altitude,this.body.stdGravParam)};b.prototype.nightTime=function(){return Orbital.orbitalNightTime(this.body.radius,this.altitude,this.body.stdGravParam)};b.prototype.requiredBattery=
function(){return(this.elcConsumption+this.antenna.elcConsumption)*this.nightTime()};b.prototype.requiredGenerator=function(){return(this.elcConsumption+this.antenna.elcConsumption)*this.orbitalPeriod()/(this.orbitalPeriod()-this.nightTime())};b.prototype.hohmannStartDeltaV=function(){return Orbital.hohmannStartDeltaV(this.body.radius,this.parkingAltitude,this.altitude,this.body.stdGravParam)};b.prototype.hohmannFinishDeltaV=function(){return Orbital.hohmannFinishDeltaV(this.body.radius,this.parkingAltitude,
this.altitude,this.body.stdGravParam)};b.prototype.slidePhaseAngle=function(){var a=Orbital.orbitalPeriod(this.body.radius,this.parkingAltitude,this.body.stdGravParam),b=Orbital.orbitalPeriod(this.body.radius,this.altitude,this.body.stdGravParam);return Orbital.slidePhaseAngle(360/this.count,a,b)};b.prototype.slidePhaseTime=function(){return this.slidePhaseAngle()/360*Orbital.orbitalPeriod(this.body.radius,this.parkingAltitude,this.body.stdGravParam)};return b}(),InputData=function(b){function a(f){b.call(this,
a.cookieKey);this.satellites=f}__extends(a,b);a.prototype.pull=function(){this.pullBody();this.pullAntenna();this.satellites.count=parseInt($("input#count").val());this.satellites.altitude=parseFloat($("input#altitude").val());this.satellites.elcConsumption=parseFloat($("input#elcConsumption").val());this.satellites.parkingAltitude=parseFloat($("input#parkingAltitude").val())};a.prototype.pullBody=function(){this.satellites.body.name=$("input#body_name").val();this.satellites.body.color=$("input#body_color").val();
this.satellites.body.radius=parseFloat($("input#body_radius").val());this.satellites.body.stdGravParam=parseFloat($("input#body_stdGravParam").val());this.satellites.body.soi=parseFloat($("input#body_soi").val())};a.prototype.pullAntenna=function(){this.satellites.antenna.name=$("input#antenna_name").val();"omni"==$("select#antenna_type").val()?this.satellites.antenna.type=0:"dish"==$("select#antenna_type").val()&&(this.satellites.antenna.type=1);this.satellites.antenna.range=parseFloat($("input#antenna_range").val());
this.satellites.antenna.elcConsumption=parseFloat($("input#antenna_elcConsumption").val())};a.prototype.push=function(){this.pushBody();this.pushAntenna();$("input#count").val(this.satellites.count.toString());$("input#altitude").val(this.satellites.altitude.toString());$("input#elcConsumption").val(this.satellites.elcConsumption.toString());$("input#parkingAltitude").val(this.satellites.parkingAltitude.toString())};a.prototype.pushBody=function(){$("select#body").val(this.satellites.body.name);$("input#body_name").val(this.satellites.body.name);
$("input#body_color").val(this.satellites.body.color);$("input#body_radius").val(this.satellites.body.radius.toString());$("input#body_stdGravParam").val(this.satellites.body.stdGravParam.toString());$("input#body_soi").val(this.satellites.body.soi.toString())};a.prototype.pushAntenna=function(){$("select#antenna").val(this.satellites.antenna.name);$("input#antenna_name").val(this.satellites.antenna.name);0==this.satellites.antenna.type?$("select#antenna_type").val("omni"):1==this.satellites.antenna.type&&
$("select#antenna_type").val("dish");$("input#antenna_range").val(this.satellites.antenna.range.toString());$("input#antenna_elcConsumption").val(this.satellites.antenna.elcConsumption.toString())};a.prototype.reset=function(){$("select#body").val("Kerbin");$("input#count").val((4).toString());$("input#altitude").val((1E3).toString());$("input#elcConsumption").val((0.01).toString());$("select#antenna").val("Communotron 16");$("input#parkingAltitude").val((70).toString())};a.prototype.save=function(){this.saveCookie(this.satellites)};
a.prototype.load=function(){var a=this.loadCookie();if(void 0==a)return!1;this.satellites.body=a.body;this.satellites.count=a.count;this.satellites.altitude=a.altitude;this.satellites.antenna=a.antenna;this.satellites.elcConsumption=a.elcConsumption;this.satellites.parkingAltitude=a.parkingAltitude;return!0};a.cookieKey="inputData";return a}(CookieConnector),GraphicsHelper;
(function(b){function a(a,b,g,h,k){a.moveTo(b,g).lineTo(b+k*Math.cos(h+f),g+k*Math.sin(h+f)).lineTo(b+k*Math.cos(h-f),g+k*Math.sin(h-f)).lineTo(b,g);return a}var f=Math.PI/6;b.drawArrow=a;b.drawDualArrow=function(b,f,g,h,k,l){var q=Math.atan2(k-g,h-f);b.moveTo(f,g).lineTo(h,k);a(b,f,g,q,l);a(b,h,k,q+Math.PI,l);return b}})(GraphicsHelper||(GraphicsHelper={}));
var View=function(){function b(a,b,c){this.stage=a;this.shapes=new createjs.Container;this.texts=new createjs.Container;this.stage.addChild(this.shapes);this.stage.addChild(this.texts);this.innerSize=b;this.outerSize=c}Object.defineProperty(b.prototype,"innerCenter",{get:function(){return new Point(this.innerSize/2,this.innerSize/2)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"outerCenter",{get:function(){return new Point(this.outerSize/2,this.outerSize/2)},enumerable:!0,configurable:!0});
b.prototype.toInner=function(a){return a*this.innerSize/this.outerSize};b.prototype.toOuter=function(a){return a*this.outerSize/this.innerSize};b.prototype.update=function(){this.stage.update()};b.fontSetNormal="16px Arial";b.fontSetBig="20px Arial";b.localeSetting={maximumFractionDigits:3};b.marginText=8;b.marginTextPushed=24;b.strokeLineWidth=0.8;b.dotRadius=4;b.arrowSize=20;return b}(),DeltavView=function(b){function a(f,c,d,g){b.call(this,f,c,d);this.satellites=g;this.shapeOuter=new createjs.Shape;
this.shapes.addChild(this.shapeOuter);this.txtDV1=new createjs.Text("",View.fontSetNormal);this.txtDV1.textAlign="left";this.txtDV1.textBaseline="middle";this.txtDV1.x=this.outerCenter.x+a.parkingAltitude+View.marginText;this.txtDV1.y=this.outerCenter.y;this.texts.addChild(this.txtDV1);this.txtDV2=new createjs.Text("",View.fontSetNormal);this.txtDV2.textAlign="left";this.txtDV2.textBaseline="middle";this.txtDV2.x=this.outerCenter.x-a.designatedAltitude+View.marginText;this.txtDV2.y=this.outerCenter.y;
this.texts.addChild(this.txtDV2);this.txtPhaseAngle=new createjs.Text("",View.fontSetNormal);this.txtPhaseAngle.textAlign="center";this.txtPhaseAngle.textBaseline="bottom";this.txtPhaseAngle.x=this.outerCenter.x;this.txtPhaseAngle.y=this.outerCenter.y-a.designatedAltitude-View.marginText;this.texts.addChild(this.txtPhaseAngle);this.txtPhaseTime=new createjs.Text("",View.fontSetNormal);this.txtPhaseTime.textAlign="center";this.txtPhaseTime.textBaseline="top";this.txtPhaseTime.x=this.outerCenter.x;
this.txtPhaseTime.y=this.outerCenter.y+a.designatedAltitude+View.marginText;this.texts.addChild(this.txtPhaseTime)}__extends(a,b);a.prototype.show=function(){this.shapeOuter.graphics.clear();this.shapeOuter.graphics.setStrokeStyle(View.strokeLineWidth);this.showFigures(this.shapeOuter.graphics,this.satellites,this.satellites.body);this.update()};a.prototype.showFigures=function(b,c,d){this.shapeOuter.graphics.beginFill(d.color).drawCircle(this.outerCenter.x,this.outerCenter.y,a.bodyRadius).endFill();
this.shapeOuter.graphics.beginStroke("black").drawCircle(this.outerCenter.x,this.outerCenter.y,a.parkingAltitude).endStroke();this.shapeOuter.graphics.beginStroke("black").drawCircle(this.outerCenter.x,this.outerCenter.y,a.designatedAltitude).endStroke();this.shapeOuter.graphics.beginStroke("green").arc(this.outerCenter.x+(a.parkingAltitude-a.designatedAltitude)/2,this.outerCenter.y,(a.parkingAltitude+a.designatedAltitude)/2,0,Math.PI,!0).endStroke();this.shapeOuter.graphics.beginStroke("green");
GraphicsHelper.drawArrow(this.shapeOuter.graphics,this.outerCenter.x+(a.parkingAltitude-a.designatedAltitude)/2,this.outerCenter.y-(a.parkingAltitude+a.designatedAltitude)/2,0,View.arrowSize).endStroke();this.txtDV1.text="Start dV:\n"+(1E3*c.hohmannStartDeltaV()).toLocaleString("en",View.localeSetting)+" m/s";this.txtDV2.text="Finish dV:\n"+(1E3*c.hohmannFinishDeltaV()).toLocaleString("en",View.localeSetting)+" m/s";this.shapeOuter.graphics.beginStroke("black").drawCircle(this.outerCenter.x-a.designatedAltitude,
this.outerCenter.y,View.dotRadius).endStroke();this.shapeOuter.graphics.beginFill("black").drawCircle(this.outerCenter.x-Math.cos(a.neighborSatInterval)*a.designatedAltitude,this.outerCenter.y-Math.sin(a.neighborSatInterval)*a.designatedAltitude,View.dotRadius).drawCircle(this.outerCenter.x-Math.cos(a.neighborSatInterval)*a.designatedAltitude,this.outerCenter.y+Math.sin(a.neighborSatInterval)*a.designatedAltitude,View.dotRadius).endFill();this.txtPhaseAngle.text="Slide angle: "+c.slidePhaseAngle().toLocaleString("en",
View.localeSetting)+" deg.";this.txtPhaseTime.text="Slide time: "+c.slidePhaseTime().toLocaleString("en",View.localeSetting)+" sec."};a.bodyRadius=20;a.parkingAltitude=50;a.designatedAltitude=150;a.neighborSatInterval=Math.PI/3;return a}(View),EntireView=function(b){function a(a,c,d,g){b.call(this,a,c,d);this.satellites=g;this.shapeInner=new createjs.Shape;this.shapes.addChild(this.shapeInner);this.txtBodyName=new createjs.Text("",View.fontSetBig);this.txtBodyName.textAlign="center";this.txtBodyName.textBaseline=
"middle";this.txtBodyName.x=this.outerCenter.x;this.txtBodyName.y=this.outerCenter.y;this.texts.addChild(this.txtBodyName);this.txtBodySoI=new createjs.Text("",View.fontSetNormal);this.txtBodySoI.textAlign="center";this.txtBodySoI.textBaseline="top";this.txtBodySoI.x=this.outerCenter.x;this.texts.addChild(this.txtBodySoI);this.txtSatAltitude=new createjs.Text("",View.fontSetNormal);this.txtSatAltitude.textAlign="center";this.txtSatAltitude.textBaseline="top";this.txtSatAltitude.x=this.outerCenter.x;
this.texts.addChild(this.txtSatAltitude);this.txtCommDistance=new createjs.Text("",View.fontSetNormal);this.txtCommDistance.textAlign="left";this.txtCommDistance.textBaseline="top";this.texts.addChild(this.txtCommDistance);this.txtCommDistance2=new createjs.Text("",View.fontSetNormal);this.txtCommDistance2.textAlign="right";this.txtCommDistance2.textBaseline="down";this.texts.addChild(this.txtCommDistance2);this.txtCommStableRange=new createjs.Text("",View.fontSetNormal);this.txtCommStableRange.textAlign=
"center";this.txtCommStableRange.textBaseline="bottom";this.txtCommStableRange.x=this.outerCenter.x;this.texts.addChild(this.txtCommStableRange)}__extends(a,b);a.prototype.show=function(){this.shapeInner.scaleX=this.shapeInner.scaleY=this.outerSize/this.innerSize;this.shapeInner.graphics.clear();this.shapeInner.graphics.setStrokeStyle(this.toInner(View.strokeLineWidth));this.showSatellites(this.shapeInner.graphics,this.satellites,this.satellites.body,this.satellites.antenna);this.showBody(this.shapeInner.graphics,
this.satellites,this.satellites.body);this.update()};a.prototype.showBody=function(a,b,d){a.beginFill(d.color).drawCircle(this.innerCenter.x,this.innerCenter.y,d.radius).endFill();this.txtBodyName.text=d.name;d.soi!=Number.POSITIVE_INFINITY?(a.beginStroke("yellow").drawCircle(this.innerCenter.x,this.innerCenter.y,d.soi-d.radius).endStroke(),this.txtBodySoI.text="Sphere of Influence: "+(d.soi-d.radius).toLocaleString("en",View.localeSetting)+" km",this.txtBodySoI.y=this.outerCenter.y+Math.max(this.toOuter(d.soi-
d.radius)+View.marginText,this.toOuter(d.radius+b.altitude)+View.marginTextPushed)):this.txtBodySoI.text=""};a.prototype.showSatellites=function(a,b,d,g){a.beginStroke("black").drawCircle(this.innerCenter.x,this.innerCenter.y,b.altitude+d.radius).endStroke();this.txtSatAltitude.text="Altitude: "+b.altitude.toLocaleString("en",View.localeSetting)+" km";this.txtSatAltitude.y=this.outerCenter.y+this.toOuter(b.altitude+d.radius)+View.marginText;for(var h=0;h<b.count;h++)a.beginFill("black").drawCircle(this.innerCenter.x+
b.satPosition(h).x,this.innerCenter.y+b.satPosition(h).y,this.toInner(View.dotRadius)).endFill();for(h=0;h<b.count;h++)a.beginFill("rgba(255,0,0,0.1)").drawCircle(this.innerCenter.x+b.satPosition(h).x,this.innerCenter.y+b.satPosition(h).y,g.range).endFill();a.beginStroke(b.isNextSatConnectable()?"blue":"red");GraphicsHelper.drawDualArrow(this.shapeInner.graphics,this.innerCenter.x+b.satPosition(0).x,this.innerCenter.y+b.satPosition(0).y,this.innerCenter.x+b.satPosition(1).x,this.innerCenter.y+b.satPosition(1).y,
this.toInner(View.arrowSize)).endStroke();this.txtCommDistance.text="Distance: "+b.satDistance().toLocaleString("en",View.localeSetting)+" km";this.txtCommDistance.x=this.outerCenter.x+this.toOuter((b.satPosition(0).x+b.satPosition(1).x)/2)+View.marginText/2;this.txtCommDistance.y=this.outerCenter.y+this.toOuter((b.satPosition(0).y+b.satPosition(1).y)/2)+View.marginText/2;4<b.count&&(a.beginStroke(b.canConnectToSat(2)?"blue":"red"),GraphicsHelper.drawDualArrow(this.shapeInner.graphics,this.innerCenter.x+
b.satPosition(0).x,this.innerCenter.y+b.satPosition(0).y,this.innerCenter.x+b.satPosition(2).x,this.innerCenter.y+b.satPosition(2).y,this.toInner(View.arrowSize)).endStroke(),this.txtCommDistance2.text="Distance: "+b.satDistanceTo(2).toLocaleString("en",View.localeSetting)+" km",this.txtCommDistance2.x=this.outerCenter.x+this.toOuter((b.satPosition(0).x+b.satPosition(2).x)/2)-View.marginText/2,this.txtCommDistance2.y=this.outerCenter.y+this.toOuter((b.satPosition(0).y+b.satPosition(2).y)/2)-View.marginText/
2);b.hasStableArea()?(this.shapeInner.graphics.beginStroke("green").drawCircle(this.innerCenter.x,this.innerCenter.y,b.stableLimitAltitude()+d.radius).endStroke(),this.txtCommStableRange.text="Stable: "+b.stableLimitAltitude().toLocaleString("en",View.localeSetting)+" km",this.txtCommStableRange.y=this.outerCenter.y-this.toOuter(b.stableLimitAltitude()+d.radius)-View.marginText):this.txtCommStableRange.text=""};return a}(View),NightView=function(b){function a(f,c,d,g){b.call(this,f,c,d);this.satellites=
g;this.shapeOuter=new createjs.Shape;this.shapes.addChild(this.shapeOuter);this.txtOrbitalPeriod=new createjs.Text("",View.fontSetNormal);this.txtOrbitalPeriod.textAlign="center";this.txtOrbitalPeriod.textBaseline="bottom";this.txtOrbitalPeriod.x=this.outerCenter.x;this.txtOrbitalPeriod.y=this.outerCenter.y-a.orbitRadius-View.marginText;this.texts.addChild(this.txtOrbitalPeriod);this.txtRequiredGenerator=new createjs.Text("",View.fontSetNormal);this.txtRequiredGenerator.textAlign="center";this.txtRequiredGenerator.textBaseline=
"top";this.txtRequiredGenerator.x=this.outerCenter.x;this.txtRequiredGenerator.y=this.outerCenter.y+a.orbitRadius+View.marginText;this.texts.addChild(this.txtRequiredGenerator);this.txtNightTime=new createjs.Text("",View.fontSetNormal);this.txtNightTime.textAlign="right";this.txtNightTime.textBaseline="bottom";this.txtNightTime.x=this.outerSize-View.marginText;this.txtNightTime.y=this.outerCenter.y-a.bodyRadius-View.marginText;this.texts.addChild(this.txtNightTime);this.txtRequiredBattery=new createjs.Text("",
View.fontSetNormal);this.txtRequiredBattery.textAlign="right";this.txtRequiredBattery.textBaseline="top";this.txtRequiredBattery.x=this.outerSize-View.marginText;this.txtRequiredBattery.y=this.outerCenter.y+a.bodyRadius+View.marginText;this.texts.addChild(this.txtRequiredBattery)}__extends(a,b);a.prototype.show=function(){this.shapeOuter.graphics.clear();this.shapeOuter.graphics.setStrokeStyle(View.strokeLineWidth);this.showFigures(this.shapeOuter.graphics,this.satellites,this.satellites.body);this.update()};
a.prototype.showFigures=function(b,c,d){this.shapeOuter.graphics.beginFill("rgba(0,0,0,0.2)").drawRect(this.outerCenter.x,this.outerCenter.y-a.bodyRadius,this.outerSize/2,2*a.bodyRadius).endFill();this.shapeOuter.graphics.beginFill(d.color).drawCircle(this.outerCenter.x,this.outerCenter.y,a.bodyRadius).endFill();this.shapeOuter.graphics.beginStroke("gray").drawCircle(this.outerCenter.x,this.outerCenter.y,a.orbitRadius).endStroke();this.txtOrbitalPeriod.text="Orbital period: "+c.orbitalPeriod().toLocaleString("en",
View.localeSetting)+" sec.";this.txtNightTime.text="Night time: "+c.nightTime().toLocaleString("en",View.localeSetting)+" sec.";this.txtRequiredBattery.text="Required Battery: "+c.requiredBattery().toLocaleString("en",View.localeSetting);this.txtRequiredGenerator.text="Required Generator: "+c.requiredGenerator().toLocaleString("en",View.localeSetting)+" per sec."};a.bodyRadius=50;a.orbitRadius=150;return a}(View);$(function(){App.init()});var App;
(function(b){function a(){p.pull();p.save();s.innerSize=2.1*(e.body.radius+e.altitude+e.antenna.range);s.show();t.show();u.show()}function f(){return c()&&d()&&$("input#count,input#altitude,input#elcConsumption").valid()}function c(){return $("div.manual-input#manual_body").children("div").children("input").valid()}function d(){return $("div.manual-input#manual_antenna").children("div").children("input").valid()}function g(a){a=m.getBody($("select#body").val());e.body.name=a.name;e.body.color=a.color;
e.body.radius=a.radius;e.body.stdGravParam=a.stdGravParam;e.body.soi=a.soi;p.pushBody();c()}function h(a){c()&&(p.pullBody(),void 0==m.stockBodies[e.body.name]&&(void 0==m.userBodies[e.body.name]&&r("body",e.body.name),$("select#body").val(e.body.name),m.userBodies[e.body.name]=new Body(e.body.name,e.body.color,e.body.radius,e.body.stdGravParam,e.body.soi),m.save()))}function k(a){$("input#body_name").valid()&&(delete m.userBodies[$("input#body_name").val()],m.save(),v("body",$("input#body_name").val()))}
function l(a){a=n.getAntenna($("select#antenna").val());e.antenna.name=a.name;e.antenna.type=a.type;e.antenna.range=a.range;e.antenna.elcConsumption=a.elcConsumption;p.pushAntenna();d()}function q(a){d()&&(p.pullAntenna(),void 0==n.stockAntennas[e.antenna.name]&&(void 0==n.userAntennas[e.antenna.name]&&r("antenna",e.antenna.name),$("select#antenna").val(e.antenna.name),n.userAntennas[e.antenna.name]=new Antenna(e.antenna.name,e.antenna.type,e.antenna.range,e.antenna.elcConsumption),n.save()))}function w(a){$("input#antenna_name").valid()&&
(delete n.userAntennas[$("input#antenna_name").val()],n.save(),v("antenna",$("input#antenna_name").val()))}function r(a,b){$("select#"+a+" \x3e optgroup[label\x3d'User data']").append("\x3coption\x3e"+b+"\x3c/option\x3e")}function v(a,b){$("optgroup[label\x3d'User data'] \x3e option:contains('"+b+"')").remove()}var e,p,m,n,s,t,u;b.init=function(){e=new Satellites;p=new InputData(e);m=new BodyData;n=new AntennaData;s=new EntireView(new createjs.Stage($("canvas#entire")[0]),1E4,840,e);t=new NightView(new createjs.Stage($("canvas#night")[0]),
5E3,400,e);u=new DeltavView(new createjs.Stage($("canvas#deltav")[0]),5E3,400,e);if(m.load())for(var b in m.userBodies)r("body",m.getBody(b).name);if(n.load())for(var c in n.userAntennas)r("antenna",n.getAntenna(c).name);$("form#calculator").validate({highlight:function(a){$(a).parent("div").addClass("has-error")},unhighlight:function(a){$(a).parent("div").removeClass("has-error")}});$("select#body").change(g);$("button.manual-input#body_detail").click(function(a){$("div.manual-input#manual_body").slideToggle()});
$("button.manual-input#body_reset").click(function(a){g(a)});$("button.manual-input#body_add").click(h);$("button.manual-input#body_remove").click(k);$("select#antenna").change(l);$("button.manual-input#antenna_detail").click(function(a){$("div.manual-input#manual_antenna").slideToggle()});$("button.manual-input#antenna_reset").click(function(a){l(a)});$("button.manual-input#antenna_add").click(q);$("button.manual-input#antenna_remove").click(w);$("form#calculator").find("input,select").keypress(function(b){13==
b.keyCode&&f()&&a()});$("button#calculate").click(function(b){f()&&a()});$("button#reset").click(function(a){});p.load()?p.push():(p.reset(),g(null),l(null));a()}})(App||(App={}));